###
### .travis.yml
###
language: node_js
node_js:
  - "10"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
 - npm install -g mocha
 - cd src/DLTGatewaySolution/NetworkListeners/FabricListener/
 - npm install

script: npm test
