###
### .travis.yml
###
language: node_js
node_js:
  - "stable"
 

before_script:
 - npm install -g mocha
 - cd src/DLTGatewaySolution/NetworkListeners/FabricListener/
 - npm install

script: npm test
