CREATE TABLE [dbo].[Role_Policy]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [RoleGUID] UNIQUEIDENTIFIER NOT NULL, 
    [PolicyGUID] UNIQUEIDENTIFIER NOT NULL, 
    [Allow] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_Role_Policy_Role] FOREIGN KEY ([RoleGUID]) REFERENCES [Role]([GUID]), 
    CONSTRAINT [FK_Role_Policy_Policy] FOREIGN KEY ([PolicyGUID]) REFERENCES [Policy]([GUID])
)
