CREATE TABLE [dbo].[User_UserGroup]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [UserGroupGUID] UNIQUEIDENTIFIER NOT NULL, 
    [UserGUID] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_User_UserGroup_UserGroup] FOREIGN KEY ([UserGroupGUID]) REFERENCES [UserGroup]([GUID]), 
    CONSTRAINT [FK_User_UserGroup_User] FOREIGN KEY ([UserGUID]) REFERENCES [User]([GUID])
)
