//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public System.Guid GUID { get; set; }
        public string OperationType { get; set; }
        public string PrimaryObjectName { get; set; }
        public System.Guid PrimaryObjectGUID { get; set; }
        public string SecondaryObjectName { get; set; }
        public Nullable<System.Guid> SecondaryObjectGUID { get; set; }
        public string OldRecordValue { get; set; }
        public string NewRecordValue { get; set; }
        public int TransactionSequence { get; set; }
        public string ServerName { get; set; }
        public System.DateTimeOffset ServerUTC { get; set; }
        public System.Guid UserGUID { get; set; }
        public string UserName { get; set; }
    
        public virtual User User { get; set; }
    }
}
