//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessNetworkObjectProperty
    {
        public System.Guid GUID { get; set; }
        public System.Guid ObjectPropertyTypeGUID { get; set; }
        public string Name { get; set; }
        public bool Visible { get; set; }
        public bool Disabled { get; set; }
        public bool Deleted { get; set; }
        public System.Guid BusinessNetworkObjectGUID { get; set; }
        public bool IsImported { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ObjectPropertyType ObjectPropertyType { get; set; }
        public virtual BusinessNetworkObject BusinessNetworkObject { get; set; }
    }
}
