//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessNetworkObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessNetworkObject()
        {
            this.DataStore = new HashSet<DataStore>();
            this.BusinessNetworkObjectProperty = new HashSet<BusinessNetworkObjectProperty>();
            this.BusinessNetworkObjectChart = new HashSet<BusinessNetworkObjectChart>();
        }
    
        public System.Guid GUID { get; set; }
        public System.Guid BusinessNetworkNamespaceGUID { get; set; }
        public string ClassName { get; set; }
        public string Name { get; set; }
        public bool Deleted { get; set; }
        public bool IsImported { get; set; }
    
        public virtual BusinessNetworkNamespace BusinessNetworkNamespace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataStore> DataStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessNetworkObjectProperty> BusinessNetworkObjectProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessNetworkObjectChart> BusinessNetworkObjectChart { get; set; }
    }
}
