//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessNetwork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessNetwork()
        {
            this.BusinessNetworkNamespace = new HashSet<BusinessNetworkNamespace>();
            this.TransactionHistory = new HashSet<TransactionHistory>();
            this.BusinessNetwork_FileUpload = new HashSet<BusinessNetwork_FileUpload>();
        }
    
        public System.Guid GUID { get; set; }
        public System.Guid BlockchainFrameworkGUID { get; set; }
        public string Name { get; set; }
        public string ChannelName { get; set; }
        public string PeerAddress { get; set; }
        public string CryptoMaterialDirectory { get; set; }
        public string Username { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> LastBlockProcessed { get; set; }
        public bool Disabled { get; set; }
        public string Endpoint { get; set; }
    
        public virtual BlockchainFramework BlockchainFramework { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessNetworkNamespace> BusinessNetworkNamespace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionHistory> TransactionHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessNetwork_FileUpload> BusinessNetwork_FileUpload { get; set; }
    }
}
