//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Policy()
        {
            this.Role_Policy = new HashSet<Role_Policy>();
        }
    
        public System.Guid GUID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public System.Guid PolicyTypeGUID { get; set; }
        public int SortOrder { get; set; }
        public bool Deleted_ { get; set; }
    
        public virtual PolicyType PolicyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role_Policy> Role_Policy { get; set; }
    }
}
