//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_UserGroup
    {
        public System.Guid GUID { get; set; }
        public System.Guid RoleGUID { get; set; }
        public System.Guid UserGroupGUID { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> BusinessNetworkGUID { get; set; }
    
        public virtual BusinessNetwork BusinessNetwork { get; set; }
        public virtual Role Role { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
