//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionHistory()
        {
            this.DataStore = new HashSet<DataStore>();
            this.DataStoreHistory = new HashSet<DataStoreHistory>();
        }
    
        public System.Guid GUID { get; set; }
        public System.Guid BusinessNetworkGUID { get; set; }
        public string TransactionID { get; set; }
        public string Data { get; set; }
        public string ChannelName { get; set; }
        public string ChaincodeName { get; set; }
        public string Version { get; set; }
        public string MspID { get; set; }
        public string Method { get; set; }
        public string Arguments { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public string ProcessedNote { get; set; }
    
        public virtual BusinessNetwork BusinessNetwork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataStore> DataStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataStoreHistory> DataStoreHistory { get; set; }
    }
}
