//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_UserGroup
    {
        public System.Guid GUID { get; set; }
        public System.Guid UserGroupGUID { get; set; }
        public System.Guid UserGUID { get; set; }
    
        public virtual User User { get; set; }
    }
}
