//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserGroup()
        {
            this.Role_UserGroup = new HashSet<Role_UserGroup>();
            this.User_UserGroup = new HashSet<User_UserGroup>();
        }
    
        public System.Guid GUID { get; set; }
        public string Name { get; set; }
        public string SID { get; set; }
        public bool Deleted { get; set; }
        public bool IsActiveDirectory { get; set; }
        public bool IsSecurityGroup { get; set; }
        public string msDSPrincipalName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role_UserGroup> Role_UserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_UserGroup> User_UserGroup { get; set; }
    }
}
