//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBusinessNetworkFile
    {
        public System.Guid BusinessNetworkGUID { get; set; }
        public string BusinessNetworkName { get; set; }
        public System.Guid FileUploadGUID { get; set; }
        public string FileUploadName { get; set; }
        public byte[] FileUploadContent { get; set; }
        public string FileUploadTypeExtension { get; set; }
        public string FileUploadFileName { get; set; }
    }
}
