//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertiPath.BlockchainGateway.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNamespaceTransactionsPerDay
    {
        public System.Guid NamespaceGUID { get; set; }
        public string NamespaceName { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionDayName { get; set; }
        public Nullable<int> TransactionCount { get; set; }
        public System.Guid KeyGUID { get; set; }
        public System.Guid BusinessNetworkGUID { get; set; }
    }
}
